version: '3.7'
services:
    redis:
        container_name: pimcore-example-redis
        image: redis:alpine

    db:
        container_name: pimcore-example-db
        image: mariadb:10.5
        working_dir: /application
        command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-format=Barracuda, --innodb-large-prefix=1, --innodb-file-per-table=1]
        volumes:
            - pimcore-example-database:/var/lib/mysql
            - ./.docker/db:/db
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    
    
    db-test:
        container_name: pimcore-example-db-test
        image: mariadb:10.5
        working_dir: /application
        command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-format=Barracuda, --innodb-large-prefix=1, --innodb-file-per-table=1]
        volumes:
            - pimcore-example-database:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD_TEST}"
            - "MYSQL_DATABASE=${MYSQL_DATABASE_TEST}"
            - "MYSQL_USER=${MYSQL_USER_TEST}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD_TEST}"

    nginx:
        container_name: pimcore-example-nginx
        image: nginx:stable-alpine
        ports:
            - "${NGINX_PORT}:80"
            - "${NGINX_PORT_SSL}:443"
        volumes:
            - .:/var/www/html:cached
            - ./.docker/dev/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php-fpm
            - php-fpm-debug

    php-fpm:
        container_name: pimcore-example-php
        build:
            context: .docker/dev/php
            dockerfile: php.Dockerfile
            args:
                UID: "${UID}"
                GID: "${GID}"
        user: "${UID}:${GID}"
        depends_on:
            - db
        volumes:
            - .:/var/www/html:cached
            - ./.docker/dev/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        environment:
            COMPOSER_HOME: /var/www/html

    php-fpm-debug:
        container_name: pimcore-example-php-debug
        build:
            context: .docker/dev/php
            dockerfile: php-debug.Dockerfile
            args:
                UID: "${UID}"
                GID: "${GID}"
                LOCAL_IP: "${LOCAL_IP}"
        user: "${UID}:${GID}"
        depends_on:
            - db
        volumes:
            - .:/var/www/html:cached
            - ./.docker/dev/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        environment:
            PHP_IDE_CONFIG: serverName=localhost
            COMPOSER_HOME: /var/www/html
    
    npm:
        container_name: pimcore-example-npm
        image: node:latest
        restart: on-failure
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        entrypoint: [ "tail", "-f", "/dev/null" ]

volumes:
    pimcore-example-database:
    pimcore-example-test-database:
